version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3300:3300'
    command: npm run start:dev
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: mysql:latest
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: market565
      MYSQL_DATABASE: mydbase
    ports:
      - '3307:3306'
    restart: always
